In [28]:
# Creating DataFrames

In [69]:
## From Dictionary


import numpy as np
import pandas as pd


data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}


df1 = pd.DataFrame(data)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [70]:
## From list

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

col_header = ["Name", "Age", "City", "Salary"]

df2 = pd.DataFrame(data_list, columns=col_header)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [71]:
# Selecting and Indexing of Columns

In [72]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [73]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [74]:
## Adding New columns

df2["Hobby"] = ["Cricket", "BaseBAll","football","Being_cat"]
df2

    Name  Age      City  Salary      Hobby
0   John   28  New York   65000    Cricket
1   Anna   34     Paris   70000   BaseBAll
2  Peter   29    Berlin   62000   football
3  Linda   42    London   85000  Being_cat

In [75]:
#Removing col/rows

In [76]:
df2.drop("City", axis=1, inplace=True)
df2

    Name  Age  Salary      Hobby
0   John   28   65000    Cricket
1   Anna   34   70000   BaseBAll
2  Peter   29   62000   football
3  Linda   42   85000  Being_cat

In [77]:
df2.drop(["Name","Age"],axis=1)

   Salary      Hobby
0   65000    Cricket
1   70000   BaseBAll
2   62000   football
3   85000  Being_cat

In [78]:
df2

    Name  Age  Salary      Hobby
0   John   28   65000    Cricket
1   Anna   34   70000   BaseBAll
2  Peter   29   62000   football
3  Linda   42   85000  Being_cat

In [79]:
df2.drop(2,axis=0)

    Name  Age  Salary      Hobby
0   John   28   65000    Cricket
1   Anna   34   70000   BaseBAll
3  Linda   42   85000  Being_cat

In [80]:
#Selcting Rows

df2

    Name  Age  Salary      Hobby
0   John   28   65000    Cricket
1   Anna   34   70000   BaseBAll
2  Peter   29   62000   football
3  Linda   42   85000  Being_cat

In [81]:
df2.loc[[2,3]]

    Name  Age  Salary      Hobby
2  Peter   29   62000   football
3  Linda   42   85000  Being_cat

In [82]:
#Selecting Subsets of rows and columns

In [83]:
df2.loc[[0,1]][["Salary","Hobby"]]

   Salary     Hobby
0   65000   Cricket
1   70000  BaseBAll

In [84]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [85]:
# Conditional Selection
df2

    Name  Age  Salary      Hobby
0   John   28   65000    Cricket
1   Anna   34   70000   BaseBAll
2  Peter   29   62000   football
3  Linda   42   85000  Being_cat

In [86]:
df2[df2["Age"] > 30]

    Name  Age  Salary      Hobby
1   Anna   34   70000   BaseBAll
3  Linda   42   85000  Being_cat

In [88]:
df2[(df2["Age"] > 30) & (df2["Salary"] > 70000)]

    Name  Age  Salary      Hobby
3  Linda   42   85000  Being_cat