# Missing Data

In [28]:
import numpy as np
import pandas as pd

## Finding

In [29]:
# Sample data dictionary
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [31]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [32]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

## Removing

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [34]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [35]:
df.dropna(thresh= 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## Filling

In [36]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [37]:
df.fillna(1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

In [38]:
v = {'A': 34, 'B':22, 'C': 99, 'D': 88}

df.fillna(value= v)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  88.0
2  34.0  3   3.0  88.0
3   4.0  4  99.0  88.0
4   5.0  5  99.0   5.0

In [39]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0