In [3]:
import numpy as np
import pandas as pd

# Basic Operations on DataFrames

In [4]:
#sample data
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [6]:
df.shape

(5, 3)

In [7]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [9]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [12]:
## broadcasting on column
df[["A","B"]] + 10

    A   B
0  11  20
1  12  30
2  13  40
3  14  50
4  15  60

In [15]:
# applying functions

def square(x):
    return x**2

df["B"]=df["B"].apply(square)
df

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [20]:
df["D"] = df["A"].apply( lambda x : x + 10)
df

   A     B    C   D
0  1   100  100  11
1  2   400  200  12
2  3   900  300  13
3  4  1600  400  14
4  5  2500  500  15